/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface TuzakaiSocialLinks {
    /** @nullable */
    instagram: string | null;
    /** @nullable */
    facebook: string | null;
    /** @nullable */
    pinterest: string | null;
    /** @nullable */
    youtube: string | null;
    /** @nullable */
    tiktok: string | null;
}
export interface TuzakaiPublicSettings {
    websiteUrl: string;
    /** @nullable */
    supportEmail: string | null;
    /** @nullable */
    businessEmail: string | null;
    socialLinks: TuzakaiSocialLinks;
}
export interface TuzakaiAdminSettings {
    websiteUrl: string;
    /** @nullable */
    supportEmail: string | null;
    /** @nullable */
    businessEmail: string | null;
    socialLinks: TuzakaiSocialLinks;
    updatedAt: string;
}
export interface TuzakaiSettingsUpdate {
    /** @maxLength 300 */
    websiteUrl: string;
    /**
       * @maxLength 254
       * @nullable
       */
    supportEmail: string | null;
    /**
       * @maxLength 254
       * @nullable
       */
    businessEmail: string | null;
    socialLinks: TuzakaiSocialLinks;
}
export interface JewelryComponent {
    id: string;
    name: string;
    category: string;
    jewelryTypes: string[];
    material: string;
    color: string;
    size: string;
    unit: string;
    /** @nullable */
    priceCents: number | null;
    /** @nullable */
    supplier: string | null;
    /** @nullable */
    supplierUrl: string | null;
    /** @nullable */
    imageUrl: string | null;
    /** @nullable */
    weightGrams: number | null;
    /** @nullable */
    inventoryQuantity: number | null;
    notes: string;
    active: boolean;
}
export type JewelryDesignInputPriceOverrides = {
    [key: string]: number;
};
export interface JewelryDesignInput {
    /** @minLength 1 */
    jewelryType: string;
    /** @minLength 1 */
    style: string;
    /** @minLength 1 */
    shape: string;
    /** @minLength 1 */
    material: string;
    /** @minLength 1 */
    color: string;
    /** @minLength 1 */
    decoration: string;
    /** @minLength 1 */
    finding: string;
    /** @minLength 1 */
    size: string;
    /** @maxLength 32 */
    personalization?: string;
    /**
       * @minimum 0
       * @nullable
       */
    budgetCents?: number | null;
    /**
       * @minimum 1
       * @maximum 100
       */
    quantity: number;
    priceOverrides: JewelryDesignInputPriceOverrides;
    /**
       * @minimum 0
       * @maximum 100
       */
    wastagePercent: number;
    /** @minimum 0 */
    laborMinutes: number;
    /** @minimum 0 */
    hourlyRateCents: number;
    /** @minimum 0 */
    packagingCents: number;
    /** @minimum 0 */
    otherCents: number;
    /**
       * @minimum 0
       * @maximum 99
       */
    marginPercent: number;
    /**
       * @minimum 0
       * @maximum 99
       */
    platformFeePercent: number;
    /**
       * @minimum 0
       * @maximum 99
       */
    paymentFeePercent: number;
}
export type JewelryMaterialLinePriceSource = typeof JewelryMaterialLinePriceSource[keyof typeof JewelryMaterialLinePriceSource];
export declare const JewelryMaterialLinePriceSource: {
    readonly configured: "configured";
    readonly entered: "entered";
    readonly missing: "missing";
};
export interface JewelryMaterialLine {
    componentId: string;
    name: string;
    quantity: number;
    unit: string;
    /** @nullable */
    unitPriceCents: number | null;
    /** @nullable */
    lineCostCents: number | null;
    priceSource: JewelryMaterialLinePriceSource;
}
export type JewelryCostCurrency = typeof JewelryCostCurrency[keyof typeof JewelryCostCurrency];
export declare const JewelryCostCurrency: {
    readonly PKR: "PKR";
};
export interface JewelryCost {
    /** @nullable */
    rawMaterialsCents: number | null;
    /** @nullable */
    wastageCents: number | null;
    laborCents: number;
    packagingCents: number;
    otherCents: number;
    /** @nullable */
    productionCents: number | null;
    /** @nullable */
    suggestedRetailCents: number | null;
    /** @nullable */
    estimatedProfitCents: number | null;
    /** @nullable */
    budgetRemainingCents: number | null;
    currency: JewelryCostCurrency;
}
export interface JewelryVariation {
    label: string;
    input: JewelryDesignInput;
    description: string;
    materials: JewelryMaterialLine[];
    cost: JewelryCost;
    instructions: string[];
}
export interface JewelryDesignProfile {
    name: string;
    description: string;
    input: JewelryDesignInput;
    materials: JewelryMaterialLine[];
    cost: JewelryCost;
    instructions: string[];
    suggestions: string[];
    warnings: string[];
    variations: JewelryVariation[];
    difficulty: string;
    estimatedMinutes: number;
    previewLabel: string;
}
export interface SavedJewelryDesign {
    id: string;
    name: string;
    profile: JewelryDesignProfile;
    createdAt: string;
    updatedAt: string;
}
export interface DesignOverview {
    designCount: number;
    recentDesigns: SavedJewelryDesign[];
    missingCatalogPrices: number;
}
export interface DeleteResult {
    success: boolean;
}
export interface JewelryAssistantInput {
    /**
       * @minLength 3
       * @maxLength 2000
       */
    question: string;
    design?: JewelryDesignInput;
}
export interface JewelryAssistantReply {
    answer: string;
}
export interface HealthStatus {
    status: string;
}
export interface StoreCategory {
    id: string;
    name: string;
    slug: string;
    /** @nullable */
    description: string | null;
    active: boolean;
    createdAt: string;
    updatedAt: string;
}
export interface StoreCategoryInput {
    /**
       * @minLength 1
       * @maxLength 120
       */
    name: string;
    /**
       * @maxLength 160
       * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
       */
    slug: string;
    /**
       * @maxLength 2000
       * @nullable
       */
    description?: string | null;
    active?: boolean;
}
export interface StoreCategoryUpdate {
    /**
       * @minLength 1
       * @maxLength 120
       */
    name?: string;
    /**
       * @maxLength 160
       * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
       */
    slug?: string;
    /**
       * @maxLength 2000
       * @nullable
       */
    description?: string | null;
    active?: boolean;
}
export type StoreProductProductType = typeof StoreProductProductType[keyof typeof StoreProductProductType];
export declare const StoreProductProductType: {
    readonly digital: "digital";
    readonly ai_tool: "ai_tool";
};
export type StoreProductStatus = typeof StoreProductStatus[keyof typeof StoreProductStatus];
export declare const StoreProductStatus: {
    readonly draft: "draft";
    readonly published: "published";
    readonly archived: "archived";
};
export interface StoreProduct {
    id: string;
    /** @nullable */
    categoryId: string | null;
    /** @nullable */
    categoryName: string | null;
    name: string;
    slug: string;
    productType: StoreProductProductType;
    /** @nullable */
    summary: string | null;
    /** @nullable */
    description: string | null;
    features: string[];
    requirements: string[];
    /** @nullable */
    imageUrl: string | null;
    /** @nullable */
    whopProductId: string | null;
    /** @nullable */
    whopProductUrl: string | null;
    /** @nullable */
    deliveryUrl: string | null;
    /** @nullable */
    deliveryInstructions: string | null;
    status: StoreProductStatus;
    createdAt: string;
    updatedAt: string;
}
export type StoreProductInputProductType = typeof StoreProductInputProductType[keyof typeof StoreProductInputProductType];
export declare const StoreProductInputProductType: {
    readonly digital: "digital";
    readonly ai_tool: "ai_tool";
};
export type StoreProductInputStatus = typeof StoreProductInputStatus[keyof typeof StoreProductInputStatus];
export declare const StoreProductInputStatus: {
    readonly draft: "draft";
    readonly published: "published";
    readonly archived: "archived";
};
export interface StoreProductInput {
    /** @nullable */
    categoryId?: string | null;
    /**
       * @minLength 1
       * @maxLength 200
       */
    name: string;
    /**
       * @maxLength 200
       * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
       */
    slug: string;
    productType: StoreProductInputProductType;
    /**
       * @maxLength 500
       * @nullable
       */
    summary?: string | null;
    /**
       * @maxLength 10000
       * @nullable
       */
    description?: string | null;
    /** @items.maxLength 500 */
    features?: string[];
    /** @items.maxLength 500 */
    requirements?: string[];
    /** @nullable */
    imageUrl?: string | null;
    /**
       * @maxLength 200
       * @nullable
       */
    whopProductId?: string | null;
    /** @nullable */
    whopProductUrl?: string | null;
    /** @nullable */
    deliveryUrl?: string | null;
    /**
       * @maxLength 5000
       * @nullable
       */
    deliveryInstructions?: string | null;
    status?: StoreProductInputStatus;
}
export type StoreProductUpdateProductType = typeof StoreProductUpdateProductType[keyof typeof StoreProductUpdateProductType];
export declare const StoreProductUpdateProductType: {
    readonly digital: "digital";
    readonly ai_tool: "ai_tool";
};
export type StoreProductUpdateStatus = typeof StoreProductUpdateStatus[keyof typeof StoreProductUpdateStatus];
export declare const StoreProductUpdateStatus: {
    readonly draft: "draft";
    readonly published: "published";
    readonly archived: "archived";
};
export interface StoreProductUpdate {
    /** @nullable */
    categoryId?: string | null;
    /**
       * @minLength 1
       * @maxLength 200
       */
    name?: string;
    /**
       * @maxLength 200
       * @pattern ^[a-z0-9]+(?:-[a-z0-9]+)*$
       */
    slug?: string;
    productType?: StoreProductUpdateProductType;
    /**
       * @maxLength 500
       * @nullable
       */
    summary?: string | null;
    /**
       * @maxLength 10000
       * @nullable
       */
    description?: string | null;
    /** @items.maxLength 500 */
    features?: string[];
    /** @items.maxLength 500 */
    requirements?: string[];
    /** @nullable */
    imageUrl?: string | null;
    /**
       * @maxLength 200
       * @nullable
       */
    whopProductId?: string | null;
    /** @nullable */
    whopProductUrl?: string | null;
    /** @nullable */
    deliveryUrl?: string | null;
    /**
       * @maxLength 5000
       * @nullable
       */
    deliveryInstructions?: string | null;
    status?: StoreProductUpdateStatus;
}
export type StoreSupportTicketStatus = typeof StoreSupportTicketStatus[keyof typeof StoreSupportTicketStatus];
export declare const StoreSupportTicketStatus: {
    readonly new: "new";
    readonly open: "open";
    readonly answered: "answered";
    readonly closed: "closed";
};
export interface StoreSupportTicket {
    id: string;
    name: string;
    email: string;
    subject: string;
    message: string;
    /** @nullable */
    productId: string | null;
    status: StoreSupportTicketStatus;
    /** @nullable */
    adminReply: string | null;
    createdAt: string;
    updatedAt: string;
}
export interface StoreSupportTicketInput {
    /**
       * @minLength 1
       * @maxLength 160
       */
    name: string;
    /** @maxLength 254 */
    email: string;
    /**
       * @minLength 1
       * @maxLength 240
       */
    subject: string;
    /**
       * @minLength 1
       * @maxLength 10000
       */
    message: string;
    /** @nullable */
    productId?: string | null;
}
export type StoreSupportTicketUpdateStatus = typeof StoreSupportTicketUpdateStatus[keyof typeof StoreSupportTicketUpdateStatus];
export declare const StoreSupportTicketUpdateStatus: {
    readonly new: "new";
    readonly open: "open";
    readonly answered: "answered";
    readonly closed: "closed";
};
export interface StoreSupportTicketUpdate {
    status?: StoreSupportTicketUpdateStatus;
    /**
       * @maxLength 10000
       * @nullable
       */
    adminReply?: string | null;
}
export type ListStoreProductsParams = {
    category?: string;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    /**
     * @minimum 0
     */
    offset?: number;
};
export type SearchStoreProductsParams = {
    /**
     * @minLength 1
     * @maxLength 200
     */
    q: string;
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
};
//# sourceMappingURL=api.schemas.d.ts.map