/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type JewelryMaterialLinePriceSource = typeof JewelryMaterialLinePriceSource[keyof typeof JewelryMaterialLinePriceSource];
export declare const JewelryMaterialLinePriceSource: {
    readonly configured: "configured";
    readonly entered: "entered";
    readonly missing: "missing";
};
//# sourceMappingURL=jewelryMaterialLinePriceSource.d.ts.map