/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type JewelryCostCurrency = typeof JewelryCostCurrency[keyof typeof JewelryCostCurrency];
export declare const JewelryCostCurrency: {
    readonly PKR: "PKR";
};
//# sourceMappingURL=jewelryCostCurrency.d.ts.map