/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreProductStatus = typeof StoreProductStatus[keyof typeof StoreProductStatus];
export declare const StoreProductStatus: {
    readonly draft: "draft";
    readonly published: "published";
    readonly archived: "archived";
};
//# sourceMappingURL=storeProductStatus.d.ts.map