/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreSupportTicketUpdateStatus = typeof StoreSupportTicketUpdateStatus[keyof typeof StoreSupportTicketUpdateStatus];
export declare const StoreSupportTicketUpdateStatus: {
    readonly new: "new";
    readonly open: "open";
    readonly answered: "answered";
    readonly closed: "closed";
};
//# sourceMappingURL=storeSupportTicketUpdateStatus.d.ts.map