/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreSupportTicketStatus = typeof StoreSupportTicketStatus[keyof typeof StoreSupportTicketStatus];
export declare const StoreSupportTicketStatus: {
    readonly new: "new";
    readonly open: "open";
    readonly answered: "answered";
    readonly closed: "closed";
};
//# sourceMappingURL=storeSupportTicketStatus.d.ts.map