/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreProductUpdateProductType = typeof StoreProductUpdateProductType[keyof typeof StoreProductUpdateProductType];
export declare const StoreProductUpdateProductType: {
    readonly digital: "digital";
    readonly ai_tool: "ai_tool";
};
//# sourceMappingURL=storeProductUpdateProductType.d.ts.map