/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreProductUpdateStatus = typeof StoreProductUpdateStatus[keyof typeof StoreProductUpdateStatus];
export declare const StoreProductUpdateStatus: {
    readonly draft: "draft";
    readonly published: "published";
    readonly archived: "archived";
};
//# sourceMappingURL=storeProductUpdateStatus.d.ts.map