/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreProductInputStatus = typeof StoreProductInputStatus[keyof typeof StoreProductInputStatus];
export declare const StoreProductInputStatus: {
    readonly draft: "draft";
    readonly published: "published";
    readonly archived: "archived";
};
//# sourceMappingURL=storeProductInputStatus.d.ts.map