/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export type StoreProductInputProductType = typeof StoreProductInputProductType[keyof typeof StoreProductInputProductType];
export declare const StoreProductInputProductType: {
    readonly digital: "digital";
    readonly ai_tool: "ai_tool";
};
//# sourceMappingURL=storeProductInputProductType.d.ts.map